language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env: AUTHOR_TESTING=1
before_install:
  - cpanm HTTP::Message
  - cpanm JSON::PP
  - cpanm LWP::UserAgent
  - cpanm Perl6::Slurp
  - cpanm Sub::Install
  - cpanm Test::MinimumVersion
  - cpanm Test::Pod
  - cpanm Test::Pod::Coverage
  - cpanm Test::Strict
  - cpanm Test::Synopsis
  - cpanm URI::Escape

branches:
  only:
    - master
